src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="cart")
     */
    public function index(SessionInterface $session, ProductRepository $productRepository): Response
    {
        // $session = new Session();
        // $session->clear();
        $cart  = $session->get('cart', []);

        $cart_view = array_count_values($cart);
      
        foreach ($cart_view as $key => $value) {
            $newCart[] = [
                'product' => $productRepository->find($key),
                'quantity'=> $value
            ];
        }

        return $this->render('cart/index.html.twig', [
            'cart' => $newCart,
        ]);
    }
    

    /**
     * @Route("/cart/add/{id}", name="addToCart")
     */
    public function add(Request $request, SessionInterface $session, $id, ProductRepository $productRepository): Response
    {

        $cart  = $session->get('cart', []);

        $arrayCart = (array) $cart;
        array_push($arrayCart, $id);
        $session->set('cart', $arrayCart);

        $this->addFlash('success', 'Produit ajouté au panier');
        $products = $productRepository->findAll();
        return $this->render('home.html.twig', [
            'products' => $products
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CartController!{% endblock %}

{% block body %}


<div class="container">
    <div class="row">
        <div class="col-6">
            <button onClick="window.history.back();" class="btn btn-warning" type="button">Retour</button>
        </div>
    </div>
    <br>
    <div class="row">
        <h2>Voici le contenu de votre panier</h2>
    </div>
    <br>
    <div class="row">
     
        {% set total = 0 %}

       {% for item in cart %}
       <div class="card" style="width: 18rem;">
               <img class="rounded mx-auto d-block" src="../images/{{item.product.image}}" style="max-width: 40%" alt="">
           <div class="card-body">
               <h5 class="card-title">{{item.quantity}} x {{item.product.name}} </h5>
               <p class="card-text"> {{item.product.price / 100 }} € unitaire </p>
               <p class="card-text" style="text-align: center; color: blue; font-weight: bold;">
                   Sous-total : {% set sousTotal = item.quantity * item.product.price  / 100 %} {{ sousTotal ~ '€'}}
               </p>
               {% set total = total + sousTotal %}
           </div>
       </div>
       {% endfor %}
       

    </div>
    <br>
    <div class="row">
        <p style="color: red; font-size: 1.3em"> Total panier : {{ total ~ '€'}}</p> <br>
    </div>
    <button class="btn btn-primary"><a href="#" style="color: black;">Commander</a></button>
    <div class="row"></div>

</div>
{% endblock %}

templates/cart/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CartController!{% endblock %}

{% block body %}
<style>

</style>

<div class="example-wrapper">
    
</div>
{% endblock %}